### ISSUE TITLE
Address books are available only to the first two created users

### ISSUE THREAD

**Issue by KarpovEvgeniy** [sctg-development/sctgdesk-api-server#10]
Good day! Excellent product! I noticed the following problem - when creating a third user - this user does not have a personal address book, so he cannot use other address books (in the "Address Book" section of the RustDesk application, the selection line does not appear). The logs show the error " database.rs:693 - get_ab_personal_guide error: Error (Row Not Found)". When opening the database in the "ab" table there is no personal book entry for the third user (the first two have entries with the "name" field value as "admin's Personal Address Book" and "Personal Address Book". Most likely, when creating the third user, the program tries to create another address book with the name "Personal Address Book" and cannot, because a record with this value for the "name" field already exists. As a result, we get that we can only create 2 users who can use the address book, one of whom will be admin.

**Comment by eltorio** [comment]
@KarpovEvgeniy thank you for reporting this issue,
Could you explain the exact process you used because I have many users.  
I’ve just tried to add another one and it works.  

![IMG_0364](https://github.com/user-attachments/assets/fe077d62-dbc9-4578-bd66-fa2ee6b08803)

Please try with a fake email (different) and a fake name.  
If possible could you provide some screenshot ?

**Comment by KarpovEvgeniy** [comment]
Thanks for the answer! The problem is not in creating new users, but in the fact that the third and further users do not have a personal address book, because of this, there is no section with address books in the interface of the RustDesk program. I.e., the admin user and the user who was created by the second have personal address books and access to shared address books (if given), and for the third and further user, a personal address book is not created. I.e., users are created successfully, but do not have access to address books. Please try logging in as a third (or further) user and check the availability of address books.
![image](https://github.com/user-attachments/assets/fa9ffb38-e214-4f02-93d0-2426d6014f8b)

**Comment by aeltorio** [comment]
@KarpovEvgeniy

I transfered the issue here because it is related to the api part of `sctgdesk-server`  

Could you configure your GitHub account as an OAuth source? If possible, please follow these steps:

1. Edit the `oauth2.toml` file by filling in your GitHub information.
2. Launch `sctgdesk-server` with the environment variable `OAUTH2_CREATE_USER` set to `1`.
3. Try logging in with a GitHub user.

Does this user have a personal address book?

Ronan

**Comment by aeltorio** [comment]
7bfe5708c1508bfb89e7ab923dadd388edb94b0f will solve this issue.  
I confirmed prior to 1.1.99-42 users created via oauth have new style address book but users created via webconsole have only a legacy address book.
