### ISSUE TITLE
Auto logout when refresh browser

### ISSUE THREAD

**Issue by vielang** [sctg-development/sctgdesk-api-server#8]
When I login successfull during refresh browser then application auto logout

**Comment by aeltorio** [comment]
Hi @B-YS ,

If you successfully logged in and then hit “refresh” on your browser, the application will log you out. This happens because the web console is a Single Page Application (SPA). The login token is stored in your session memory (via Vue Pinia), and refreshing the page causes this token to be lost, resulting in you being logged out.
